// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/comet/comet.proto

package comet

import (
	protocol "github.com/Terry-Mao/goim/api/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	ProtoOp       int32                  `protobuf:"varint,3,opt,name=protoOp,proto3" json:"protoOp,omitempty"`
	Proto         *protocol.Proto        `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsgReq) Reset() {
	*x = PushMsgReq{}
	mi := &file_api_comet_comet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgReq) ProtoMessage() {}

func (x *PushMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_comet_comet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgReq.ProtoReflect.Descriptor instead.
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return file_api_comet_comet_proto_rawDescGZIP(), []int{0}
}

func (x *PushMsgReq) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *PushMsgReq) GetProtoOp() int32 {
	if x != nil {
		return x.ProtoOp
	}
	return 0
}

func (x *PushMsgReq) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

type PushMsgReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsgReply) Reset() {
	*x = PushMsgReply{}
	mi := &file_api_comet_comet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgReply) ProtoMessage() {}

func (x *PushMsgReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_comet_comet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgReply.ProtoReflect.Descriptor instead.
func (*PushMsgReply) Descriptor() ([]byte, []int) {
	return file_api_comet_comet_proto_rawDescGZIP(), []int{1}
}

type BroadcastReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtoOp       int32                  `protobuf:"varint,1,opt,name=protoOp,proto3" json:"protoOp,omitempty"`
	Proto         *protocol.Proto        `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	Speed         int32                  `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastReq) Reset() {
	*x = BroadcastReq{}
	mi := &file_api_comet_comet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastReq) ProtoMessage() {}

func (x *BroadcastReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_comet_comet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastReq.ProtoReflect.Descriptor instead.
func (*BroadcastReq) Descriptor() ([]byte, []int) {
	return file_api_comet_comet_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastReq) GetProtoOp() int32 {
	if x != nil {
		return x.ProtoOp
	}
	return 0
}

func (x *BroadcastReq) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

func (x *BroadcastReq) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type BroadcastReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastReply) Reset() {
	*x = BroadcastReply{}
	mi := &file_api_comet_comet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastReply) ProtoMessage() {}

func (x *BroadcastReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_comet_comet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastReply.ProtoReflect.Descriptor instead.
func (*BroadcastReply) Descriptor() ([]byte, []int) {
	return file_api_comet_comet_proto_rawDescGZIP(), []int{3}
}

type BroadcastRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Proto         *protocol.Proto        `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRoomReq) Reset() {
	*x = BroadcastRoomReq{}
	mi := &file_api_comet_comet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRoomReq) ProtoMessage() {}

func (x *BroadcastRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_comet_comet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRoomReq.ProtoReflect.Descriptor instead.
func (*BroadcastRoomReq) Descriptor() ([]byte, []int) {
	return file_api_comet_comet_proto_rawDescGZIP(), []int{4}
}

func (x *BroadcastRoomReq) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *BroadcastRoomReq) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

type BroadcastRoomReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRoomReply) Reset() {
	*x = BroadcastRoomReply{}
	mi := &file_api_comet_comet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRoomReply) ProtoMessage() {}

func (x *BroadcastRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_comet_comet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRoomReply.ProtoReflect.Descriptor instead.
func (*BroadcastRoomReply) Descriptor() ([]byte, []int) {
	return file_api_comet_comet_proto_rawDescGZIP(), []int{5}
}

type RoomsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomsReq) Reset() {
	*x = RoomsReq{}
	mi := &file_api_comet_comet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomsReq) ProtoMessage() {}

func (x *RoomsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_comet_comet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomsReq.ProtoReflect.Descriptor instead.
func (*RoomsReq) Descriptor() ([]byte, []int) {
	return file_api_comet_comet_proto_rawDescGZIP(), []int{6}
}

type RoomsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         map[string]bool        `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomsReply) Reset() {
	*x = RoomsReply{}
	mi := &file_api_comet_comet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomsReply) ProtoMessage() {}

func (x *RoomsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_comet_comet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomsReply.ProtoReflect.Descriptor instead.
func (*RoomsReply) Descriptor() ([]byte, []int) {
	return file_api_comet_comet_proto_rawDescGZIP(), []int{7}
}

func (x *RoomsReply) GetRooms() map[string]bool {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_api_comet_comet_proto protoreflect.FileDescriptor

const file_api_comet_comet_proto_rawDesc = "" +
	"\n" +
	"\x15api/comet/comet.proto\x12\n" +
	"goim.comet\x1a\x1bapi/protocol/protocol.proto\"f\n" +
	"\n" +
	"PushMsgReq\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x18\n" +
	"\aprotoOp\x18\x03 \x01(\x05R\aprotoOp\x12*\n" +
	"\x05proto\x18\x02 \x01(\v2\x14.goim.protocol.ProtoR\x05proto\"\x0e\n" +
	"\fPushMsgReply\"j\n" +
	"\fBroadcastReq\x12\x18\n" +
	"\aprotoOp\x18\x01 \x01(\x05R\aprotoOp\x12*\n" +
	"\x05proto\x18\x02 \x01(\v2\x14.goim.protocol.ProtoR\x05proto\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x05R\x05speed\"\x10\n" +
	"\x0eBroadcastReply\"V\n" +
	"\x10BroadcastRoomReq\x12\x16\n" +
	"\x06roomID\x18\x01 \x01(\tR\x06roomID\x12*\n" +
	"\x05proto\x18\x02 \x01(\v2\x14.goim.protocol.ProtoR\x05proto\"\x14\n" +
	"\x12BroadcastRoomReply\"\n" +
	"\n" +
	"\bRoomsReq\"\x7f\n" +
	"\n" +
	"RoomsReply\x127\n" +
	"\x05rooms\x18\x01 \x03(\v2!.goim.comet.RoomsReply.RoomsEntryR\x05rooms\x1a8\n" +
	"\n" +
	"RoomsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x012\x8d\x02\n" +
	"\x05Comet\x12;\n" +
	"\aPushMsg\x12\x16.goim.comet.PushMsgReq\x1a\x18.goim.comet.PushMsgReply\x12A\n" +
	"\tBroadcast\x12\x18.goim.comet.BroadcastReq\x1a\x1a.goim.comet.BroadcastReply\x12M\n" +
	"\rBroadcastRoom\x12\x1c.goim.comet.BroadcastRoomReq\x1a\x1e.goim.comet.BroadcastRoomReply\x125\n" +
	"\x05Rooms\x12\x14.goim.comet.RoomsReq\x1a\x16.goim.comet.RoomsReplyB+Z)github.com/Terry-Mao/goim/api/comet;cometb\x06proto3"

var (
	file_api_comet_comet_proto_rawDescOnce sync.Once
	file_api_comet_comet_proto_rawDescData []byte
)

func file_api_comet_comet_proto_rawDescGZIP() []byte {
	file_api_comet_comet_proto_rawDescOnce.Do(func() {
		file_api_comet_comet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_comet_comet_proto_rawDesc), len(file_api_comet_comet_proto_rawDesc)))
	})
	return file_api_comet_comet_proto_rawDescData
}

var file_api_comet_comet_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_comet_comet_proto_goTypes = []any{
	(*PushMsgReq)(nil),         // 0: goim.comet.PushMsgReq
	(*PushMsgReply)(nil),       // 1: goim.comet.PushMsgReply
	(*BroadcastReq)(nil),       // 2: goim.comet.BroadcastReq
	(*BroadcastReply)(nil),     // 3: goim.comet.BroadcastReply
	(*BroadcastRoomReq)(nil),   // 4: goim.comet.BroadcastRoomReq
	(*BroadcastRoomReply)(nil), // 5: goim.comet.BroadcastRoomReply
	(*RoomsReq)(nil),           // 6: goim.comet.RoomsReq
	(*RoomsReply)(nil),         // 7: goim.comet.RoomsReply
	nil,                        // 8: goim.comet.RoomsReply.RoomsEntry
	(*protocol.Proto)(nil),     // 9: goim.protocol.Proto
}
var file_api_comet_comet_proto_depIdxs = []int32{
	9, // 0: goim.comet.PushMsgReq.proto:type_name -> goim.protocol.Proto
	9, // 1: goim.comet.BroadcastReq.proto:type_name -> goim.protocol.Proto
	9, // 2: goim.comet.BroadcastRoomReq.proto:type_name -> goim.protocol.Proto
	8, // 3: goim.comet.RoomsReply.rooms:type_name -> goim.comet.RoomsReply.RoomsEntry
	0, // 4: goim.comet.Comet.PushMsg:input_type -> goim.comet.PushMsgReq
	2, // 5: goim.comet.Comet.Broadcast:input_type -> goim.comet.BroadcastReq
	4, // 6: goim.comet.Comet.BroadcastRoom:input_type -> goim.comet.BroadcastRoomReq
	6, // 7: goim.comet.Comet.Rooms:input_type -> goim.comet.RoomsReq
	1, // 8: goim.comet.Comet.PushMsg:output_type -> goim.comet.PushMsgReply
	3, // 9: goim.comet.Comet.Broadcast:output_type -> goim.comet.BroadcastReply
	5, // 10: goim.comet.Comet.BroadcastRoom:output_type -> goim.comet.BroadcastRoomReply
	7, // 11: goim.comet.Comet.Rooms:output_type -> goim.comet.RoomsReply
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_comet_comet_proto_init() }
func file_api_comet_comet_proto_init() {
	if File_api_comet_comet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_comet_comet_proto_rawDesc), len(file_api_comet_comet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_comet_comet_proto_goTypes,
		DependencyIndexes: file_api_comet_comet_proto_depIdxs,
		MessageInfos:      file_api_comet_comet_proto_msgTypes,
	}.Build()
	File_api_comet_comet_proto = out.File
	file_api_comet_comet_proto_goTypes = nil
	file_api_comet_comet_proto_depIdxs = nil
}
