# This is a TOML document. Boom
[discovery]
    nodes = ["127.0.0.1:7171"]
    env = "dev"
    region = "sh"
    zone = "sh001"

[kafka]
    topic = "goim-push-topic"
    group = "goim-push-group-job"
    brokers = ["127.0.0.1:9092"]
    pushTopic = "goim-push-topic"
    roomTopic = "goim-room-topic"
    allTopic  = "goim-all-topic"
    ackTopic  = "goim-ack-topic"
