// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/logic/logic.proto

package logic

import (
	protocol "github.com/Terry-Mao/goim/api/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushMsg_Type int32

const (
	PushMsg_PUSH      PushMsg_Type = 0
	PushMsg_ROOM      PushMsg_Type = 1
	PushMsg_BROADCAST PushMsg_Type = 2
)

// Enum value maps for PushMsg_Type.
var (
	PushMsg_Type_name = map[int32]string{
		0: "PUSH",
		1: "ROOM",
		2: "BROADCAST",
	}
	PushMsg_Type_value = map[string]int32{
		"PUSH":      0,
		"ROOM":      1,
		"BROADCAST": 2,
	}
)

func (x PushMsg_Type) Enum() *PushMsg_Type {
	p := new(PushMsg_Type)
	*p = x
	return p
}

func (x PushMsg_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushMsg_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_logic_logic_proto_enumTypes[0].Descriptor()
}

func (PushMsg_Type) Type() protoreflect.EnumType {
	return &file_api_logic_logic_proto_enumTypes[0]
}

func (x PushMsg_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushMsg_Type.Descriptor instead.
func (PushMsg_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{0, 0}
}

type PushMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PushMsg_Type           `protobuf:"varint,1,opt,name=type,proto3,enum=goim.logic.PushMsg_Type" json:"type,omitempty"`
	Operation     int32                  `protobuf:"varint,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Speed         int32                  `protobuf:"varint,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Server        string                 `protobuf:"bytes,4,opt,name=server,proto3" json:"server,omitempty"`
	Room          string                 `protobuf:"bytes,5,opt,name=room,proto3" json:"room,omitempty"`
	Keys          []string               `protobuf:"bytes,6,rep,name=keys,proto3" json:"keys,omitempty"`
	Msg           []byte                 `protobuf:"bytes,7,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsg) Reset() {
	*x = PushMsg{}
	mi := &file_api_logic_logic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsg) ProtoMessage() {}

func (x *PushMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsg.ProtoReflect.Descriptor instead.
func (*PushMsg) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{0}
}

func (x *PushMsg) GetType() PushMsg_Type {
	if x != nil {
		return x.Type
	}
	return PushMsg_PUSH
}

func (x *PushMsg) GetOperation() int32 {
	if x != nil {
		return x.Operation
	}
	return 0
}

func (x *PushMsg) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PushMsg) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *PushMsg) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *PushMsg) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *PushMsg) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type ConnectReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Cookie        string                 `protobuf:"bytes,2,opt,name=cookie,proto3" json:"cookie,omitempty"`
	Token         []byte                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectReq) Reset() {
	*x = ConnectReq{}
	mi := &file_api_logic_logic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectReq) ProtoMessage() {}

func (x *ConnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectReq.ProtoReflect.Descriptor instead.
func (*ConnectReq) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectReq) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *ConnectReq) GetCookie() string {
	if x != nil {
		return x.Cookie
	}
	return ""
}

func (x *ConnectReq) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type ConnectReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	RoomID        string                 `protobuf:"bytes,3,opt,name=roomID,proto3" json:"roomID,omitempty"`
	Accepts       []int32                `protobuf:"varint,4,rep,packed,name=accepts,proto3" json:"accepts,omitempty"`
	Heartbeat     int64                  `protobuf:"varint,5,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Sid           string                 `protobuf:"bytes,6,opt,name=sid,proto3" json:"sid,omitempty"` // session ID (new)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectReply) Reset() {
	*x = ConnectReply{}
	mi := &file_api_logic_logic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectReply) ProtoMessage() {}

func (x *ConnectReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectReply.ProtoReflect.Descriptor instead.
func (*ConnectReply) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectReply) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *ConnectReply) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConnectReply) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *ConnectReply) GetAccepts() []int32 {
	if x != nil {
		return x.Accepts
	}
	return nil
}

func (x *ConnectReply) GetHeartbeat() int64 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

func (x *ConnectReply) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

type DisconnectReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Server        string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectReq) Reset() {
	*x = DisconnectReq{}
	mi := &file_api_logic_logic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectReq) ProtoMessage() {}

func (x *DisconnectReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectReq.ProtoReflect.Descriptor instead.
func (*DisconnectReq) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{3}
}

func (x *DisconnectReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *DisconnectReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DisconnectReq) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type DisconnectReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Has           bool                   `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectReply) Reset() {
	*x = DisconnectReply{}
	mi := &file_api_logic_logic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectReply) ProtoMessage() {}

func (x *DisconnectReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectReply.ProtoReflect.Descriptor instead.
func (*DisconnectReply) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{4}
}

func (x *DisconnectReply) GetHas() bool {
	if x != nil {
		return x.Has
	}
	return false
}

type HeartbeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Server        string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_api_logic_logic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *HeartbeatReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HeartbeatReq) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type HeartbeatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	mi := &file_api_logic_logic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{6}
}

type OnlineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	RoomCount     map[string]int32       `protobuf:"bytes,2,rep,name=roomCount,proto3" json:"roomCount,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineReq) Reset() {
	*x = OnlineReq{}
	mi := &file_api_logic_logic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineReq) ProtoMessage() {}

func (x *OnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineReq.ProtoReflect.Descriptor instead.
func (*OnlineReq) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{7}
}

func (x *OnlineReq) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *OnlineReq) GetRoomCount() map[string]int32 {
	if x != nil {
		return x.RoomCount
	}
	return nil
}

type OnlineReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllRoomCount  map[string]int32       `protobuf:"bytes,1,rep,name=allRoomCount,proto3" json:"allRoomCount,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineReply) Reset() {
	*x = OnlineReply{}
	mi := &file_api_logic_logic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineReply) ProtoMessage() {}

func (x *OnlineReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineReply.ProtoReflect.Descriptor instead.
func (*OnlineReply) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{8}
}

func (x *OnlineReply) GetAllRoomCount() map[string]int32 {
	if x != nil {
		return x.AllRoomCount
	}
	return nil
}

type ReceiveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Proto         *protocol.Proto        `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveReq) Reset() {
	*x = ReceiveReq{}
	mi := &file_api_logic_logic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveReq) ProtoMessage() {}

func (x *ReceiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveReq.ProtoReflect.Descriptor instead.
func (*ReceiveReq) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{9}
}

func (x *ReceiveReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *ReceiveReq) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

type ReceiveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proto         *protocol.Proto        `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveReply) Reset() {
	*x = ReceiveReply{}
	mi := &file_api_logic_logic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveReply) ProtoMessage() {}

func (x *ReceiveReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveReply.ProtoReflect.Descriptor instead.
func (*ReceiveReply) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{10}
}

func (x *ReceiveReply) GetProto() *protocol.Proto {
	if x != nil {
		return x.Proto
	}
	return nil
}

type NodesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	ClientIP      string                 `protobuf:"bytes,2,opt,name=clientIP,proto3" json:"clientIP,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodesReq) Reset() {
	*x = NodesReq{}
	mi := &file_api_logic_logic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesReq) ProtoMessage() {}

func (x *NodesReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesReq.ProtoReflect.Descriptor instead.
func (*NodesReq) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{11}
}

func (x *NodesReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *NodesReq) GetClientIP() string {
	if x != nil {
		return x.ClientIP
	}
	return ""
}

type NodesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	TcpPort       int32                  `protobuf:"varint,2,opt,name=tcp_port,json=tcpPort,proto3" json:"tcp_port,omitempty"`
	WsPort        int32                  `protobuf:"varint,3,opt,name=ws_port,json=wsPort,proto3" json:"ws_port,omitempty"`
	WssPort       int32                  `protobuf:"varint,4,opt,name=wss_port,json=wssPort,proto3" json:"wss_port,omitempty"`
	Heartbeat     int32                  `protobuf:"varint,5,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Nodes         []string               `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Backoff       *Backoff               `protobuf:"bytes,7,opt,name=backoff,proto3" json:"backoff,omitempty"`
	HeartbeatMax  int32                  `protobuf:"varint,8,opt,name=heartbeat_max,json=heartbeatMax,proto3" json:"heartbeat_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodesReply) Reset() {
	*x = NodesReply{}
	mi := &file_api_logic_logic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodesReply) ProtoMessage() {}

func (x *NodesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodesReply.ProtoReflect.Descriptor instead.
func (*NodesReply) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{12}
}

func (x *NodesReply) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *NodesReply) GetTcpPort() int32 {
	if x != nil {
		return x.TcpPort
	}
	return 0
}

func (x *NodesReply) GetWsPort() int32 {
	if x != nil {
		return x.WsPort
	}
	return 0
}

func (x *NodesReply) GetWssPort() int32 {
	if x != nil {
		return x.WssPort
	}
	return 0
}

func (x *NodesReply) GetHeartbeat() int32 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

func (x *NodesReply) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *NodesReply) GetBackoff() *Backoff {
	if x != nil {
		return x.Backoff
	}
	return nil
}

func (x *NodesReply) GetHeartbeatMax() int32 {
	if x != nil {
		return x.HeartbeatMax
	}
	return 0
}

type Backoff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxDelay      int32                  `protobuf:"varint,1,opt,name=max_delay,json=maxDelay,proto3" json:"max_delay,omitempty"`
	BaseDelay     int32                  `protobuf:"varint,2,opt,name=base_delay,json=baseDelay,proto3" json:"base_delay,omitempty"`
	Factor        float32                `protobuf:"fixed32,3,opt,name=factor,proto3" json:"factor,omitempty"`
	Jitter        float32                `protobuf:"fixed32,4,opt,name=jitter,proto3" json:"jitter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backoff) Reset() {
	*x = Backoff{}
	mi := &file_api_logic_logic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backoff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backoff) ProtoMessage() {}

func (x *Backoff) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backoff.ProtoReflect.Descriptor instead.
func (*Backoff) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{13}
}

func (x *Backoff) GetMaxDelay() int32 {
	if x != nil {
		return x.MaxDelay
	}
	return 0
}

func (x *Backoff) GetBaseDelay() int32 {
	if x != nil {
		return x.BaseDelay
	}
	return 0
}

func (x *Backoff) GetFactor() float32 {
	if x != nil {
		return x.Factor
	}
	return 0
}

func (x *Backoff) GetJitter() float32 {
	if x != nil {
		return x.Jitter
	}
	return 0
}

type AckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckReq) Reset() {
	*x = AckReq{}
	mi := &file_api_logic_logic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckReq) ProtoMessage() {}

func (x *AckReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckReq.ProtoReflect.Descriptor instead.
func (*AckReq) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{14}
}

func (x *AckReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *AckReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *AckReq) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type AckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckReply) Reset() {
	*x = AckReply{}
	mi := &file_api_logic_logic_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckReply) ProtoMessage() {}

func (x *AckReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckReply.ProtoReflect.Descriptor instead.
func (*AckReply) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{15}
}

type SyncOfflineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mid           int64                  `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	LastSeq       int64                  `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOfflineReq) Reset() {
	*x = SyncOfflineReq{}
	mi := &file_api_logic_logic_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOfflineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOfflineReq) ProtoMessage() {}

func (x *SyncOfflineReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOfflineReq.ProtoReflect.Descriptor instead.
func (*SyncOfflineReq) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{16}
}

func (x *SyncOfflineReq) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *SyncOfflineReq) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *SyncOfflineReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SyncOfflineReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentSeq    int64                  `protobuf:"varint,1,opt,name=current_seq,json=currentSeq,proto3" json:"current_seq,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOfflineReply) Reset() {
	*x = SyncOfflineReply{}
	mi := &file_api_logic_logic_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOfflineReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOfflineReply) ProtoMessage() {}

func (x *SyncOfflineReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_logic_logic_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOfflineReply.ProtoReflect.Descriptor instead.
func (*SyncOfflineReply) Descriptor() ([]byte, []int) {
	return file_api_logic_logic_proto_rawDescGZIP(), []int{17}
}

func (x *SyncOfflineReply) GetCurrentSeq() int64 {
	if x != nil {
		return x.CurrentSeq
	}
	return 0
}

func (x *SyncOfflineReply) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_api_logic_logic_proto protoreflect.FileDescriptor

const file_api_logic_logic_proto_rawDesc = "" +
	"\n" +
	"\x15api/logic/logic.proto\x12\n" +
	"goim.logic\x1a\x1bapi/protocol/protocol.proto\"\xe8\x01\n" +
	"\aPushMsg\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.goim.logic.PushMsg.TypeR\x04type\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\x05R\toperation\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x05R\x05speed\x12\x16\n" +
	"\x06server\x18\x04 \x01(\tR\x06server\x12\x12\n" +
	"\x04room\x18\x05 \x01(\tR\x04room\x12\x12\n" +
	"\x04keys\x18\x06 \x03(\tR\x04keys\x12\x10\n" +
	"\x03msg\x18\a \x01(\fR\x03msg\")\n" +
	"\x04Type\x12\b\n" +
	"\x04PUSH\x10\x00\x12\b\n" +
	"\x04ROOM\x10\x01\x12\r\n" +
	"\tBROADCAST\x10\x02\"R\n" +
	"\n" +
	"ConnectReq\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x16\n" +
	"\x06cookie\x18\x02 \x01(\tR\x06cookie\x12\x14\n" +
	"\x05token\x18\x03 \x01(\fR\x05token\"\x94\x01\n" +
	"\fConnectReply\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06roomID\x18\x03 \x01(\tR\x06roomID\x12\x18\n" +
	"\aaccepts\x18\x04 \x03(\x05R\aaccepts\x12\x1c\n" +
	"\theartbeat\x18\x05 \x01(\x03R\theartbeat\x12\x10\n" +
	"\x03sid\x18\x06 \x01(\tR\x03sid\"K\n" +
	"\rDisconnectReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\"#\n" +
	"\x0fDisconnectReply\x12\x10\n" +
	"\x03has\x18\x01 \x01(\bR\x03has\"J\n" +
	"\fHeartbeatReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\"\x10\n" +
	"\x0eHeartbeatReply\"\xa5\x01\n" +
	"\tOnlineReq\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12B\n" +
	"\troomCount\x18\x02 \x03(\v2$.goim.logic.OnlineReq.RoomCountEntryR\troomCount\x1a<\n" +
	"\x0eRoomCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x9d\x01\n" +
	"\vOnlineReply\x12M\n" +
	"\fallRoomCount\x18\x01 \x03(\v2).goim.logic.OnlineReply.AllRoomCountEntryR\fallRoomCount\x1a?\n" +
	"\x11AllRoomCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"J\n" +
	"\n" +
	"ReceiveReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12*\n" +
	"\x05proto\x18\x02 \x01(\v2\x14.goim.protocol.ProtoR\x05proto\":\n" +
	"\fReceiveReply\x12*\n" +
	"\x05proto\x18\x01 \x01(\v2\x14.goim.protocol.ProtoR\x05proto\"B\n" +
	"\bNodesReq\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1a\n" +
	"\bclientIP\x18\x02 \x01(\tR\bclientIP\"\xfb\x01\n" +
	"\n" +
	"NodesReply\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x19\n" +
	"\btcp_port\x18\x02 \x01(\x05R\atcpPort\x12\x17\n" +
	"\aws_port\x18\x03 \x01(\x05R\x06wsPort\x12\x19\n" +
	"\bwss_port\x18\x04 \x01(\x05R\awssPort\x12\x1c\n" +
	"\theartbeat\x18\x05 \x01(\x05R\theartbeat\x12\x14\n" +
	"\x05nodes\x18\x06 \x03(\tR\x05nodes\x12-\n" +
	"\abackoff\x18\a \x01(\v2\x13.goim.logic.BackoffR\abackoff\x12#\n" +
	"\rheartbeat_max\x18\b \x01(\x05R\fheartbeatMax\"u\n" +
	"\aBackoff\x12\x1b\n" +
	"\tmax_delay\x18\x01 \x01(\x05R\bmaxDelay\x12\x1d\n" +
	"\n" +
	"base_delay\x18\x02 \x01(\x05R\tbaseDelay\x12\x16\n" +
	"\x06factor\x18\x03 \x01(\x02R\x06factor\x12\x16\n" +
	"\x06jitter\x18\x04 \x01(\x02R\x06jitter\"C\n" +
	"\x06AckReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\"\n" +
	"\n" +
	"\bAckReply\"S\n" +
	"\x0eSyncOfflineReq\x12\x10\n" +
	"\x03mid\x18\x01 \x01(\x03R\x03mid\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x03R\alastSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"N\n" +
	"\x10SyncOfflineReply\x12\x1f\n" +
	"\vcurrent_seq\x18\x01 \x01(\x03R\n" +
	"currentSeq\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore2\x81\x04\n" +
	"\x05Logic\x12;\n" +
	"\aConnect\x12\x16.goim.logic.ConnectReq\x1a\x18.goim.logic.ConnectReply\x12D\n" +
	"\n" +
	"Disconnect\x12\x19.goim.logic.DisconnectReq\x1a\x1b.goim.logic.DisconnectReply\x12A\n" +
	"\tHeartbeat\x12\x18.goim.logic.HeartbeatReq\x1a\x1a.goim.logic.HeartbeatReply\x12=\n" +
	"\vRenewOnline\x12\x15.goim.logic.OnlineReq\x1a\x17.goim.logic.OnlineReply\x12;\n" +
	"\aReceive\x12\x16.goim.logic.ReceiveReq\x1a\x18.goim.logic.ReceiveReply\x125\n" +
	"\x05Nodes\x12\x14.goim.logic.NodesReq\x1a\x16.goim.logic.NodesReply\x126\n" +
	"\n" +
	"AckMessage\x12\x12.goim.logic.AckReq\x1a\x14.goim.logic.AckReply\x12G\n" +
	"\vSyncOffline\x12\x1a.goim.logic.SyncOfflineReq\x1a\x1c.goim.logic.SyncOfflineReplyB+Z)github.com/Terry-Mao/goim/api/logic;logicb\x06proto3"

var (
	file_api_logic_logic_proto_rawDescOnce sync.Once
	file_api_logic_logic_proto_rawDescData []byte
)

func file_api_logic_logic_proto_rawDescGZIP() []byte {
	file_api_logic_logic_proto_rawDescOnce.Do(func() {
		file_api_logic_logic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_logic_logic_proto_rawDesc), len(file_api_logic_logic_proto_rawDesc)))
	})
	return file_api_logic_logic_proto_rawDescData
}

var file_api_logic_logic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_logic_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_logic_logic_proto_goTypes = []any{
	(PushMsg_Type)(0),        // 0: goim.logic.PushMsg.Type
	(*PushMsg)(nil),          // 1: goim.logic.PushMsg
	(*ConnectReq)(nil),       // 2: goim.logic.ConnectReq
	(*ConnectReply)(nil),     // 3: goim.logic.ConnectReply
	(*DisconnectReq)(nil),    // 4: goim.logic.DisconnectReq
	(*DisconnectReply)(nil),  // 5: goim.logic.DisconnectReply
	(*HeartbeatReq)(nil),     // 6: goim.logic.HeartbeatReq
	(*HeartbeatReply)(nil),   // 7: goim.logic.HeartbeatReply
	(*OnlineReq)(nil),        // 8: goim.logic.OnlineReq
	(*OnlineReply)(nil),      // 9: goim.logic.OnlineReply
	(*ReceiveReq)(nil),       // 10: goim.logic.ReceiveReq
	(*ReceiveReply)(nil),     // 11: goim.logic.ReceiveReply
	(*NodesReq)(nil),         // 12: goim.logic.NodesReq
	(*NodesReply)(nil),       // 13: goim.logic.NodesReply
	(*Backoff)(nil),          // 14: goim.logic.Backoff
	(*AckReq)(nil),           // 15: goim.logic.AckReq
	(*AckReply)(nil),         // 16: goim.logic.AckReply
	(*SyncOfflineReq)(nil),   // 17: goim.logic.SyncOfflineReq
	(*SyncOfflineReply)(nil), // 18: goim.logic.SyncOfflineReply
	nil,                      // 19: goim.logic.OnlineReq.RoomCountEntry
	nil,                      // 20: goim.logic.OnlineReply.AllRoomCountEntry
	(*protocol.Proto)(nil),   // 21: goim.protocol.Proto
}
var file_api_logic_logic_proto_depIdxs = []int32{
	0,  // 0: goim.logic.PushMsg.type:type_name -> goim.logic.PushMsg.Type
	19, // 1: goim.logic.OnlineReq.roomCount:type_name -> goim.logic.OnlineReq.RoomCountEntry
	20, // 2: goim.logic.OnlineReply.allRoomCount:type_name -> goim.logic.OnlineReply.AllRoomCountEntry
	21, // 3: goim.logic.ReceiveReq.proto:type_name -> goim.protocol.Proto
	21, // 4: goim.logic.ReceiveReply.proto:type_name -> goim.protocol.Proto
	14, // 5: goim.logic.NodesReply.backoff:type_name -> goim.logic.Backoff
	2,  // 6: goim.logic.Logic.Connect:input_type -> goim.logic.ConnectReq
	4,  // 7: goim.logic.Logic.Disconnect:input_type -> goim.logic.DisconnectReq
	6,  // 8: goim.logic.Logic.Heartbeat:input_type -> goim.logic.HeartbeatReq
	8,  // 9: goim.logic.Logic.RenewOnline:input_type -> goim.logic.OnlineReq
	10, // 10: goim.logic.Logic.Receive:input_type -> goim.logic.ReceiveReq
	12, // 11: goim.logic.Logic.Nodes:input_type -> goim.logic.NodesReq
	15, // 12: goim.logic.Logic.AckMessage:input_type -> goim.logic.AckReq
	17, // 13: goim.logic.Logic.SyncOffline:input_type -> goim.logic.SyncOfflineReq
	3,  // 14: goim.logic.Logic.Connect:output_type -> goim.logic.ConnectReply
	5,  // 15: goim.logic.Logic.Disconnect:output_type -> goim.logic.DisconnectReply
	7,  // 16: goim.logic.Logic.Heartbeat:output_type -> goim.logic.HeartbeatReply
	9,  // 17: goim.logic.Logic.RenewOnline:output_type -> goim.logic.OnlineReply
	11, // 18: goim.logic.Logic.Receive:output_type -> goim.logic.ReceiveReply
	13, // 19: goim.logic.Logic.Nodes:output_type -> goim.logic.NodesReply
	16, // 20: goim.logic.Logic.AckMessage:output_type -> goim.logic.AckReply
	18, // 21: goim.logic.Logic.SyncOffline:output_type -> goim.logic.SyncOfflineReply
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_logic_logic_proto_init() }
func file_api_logic_logic_proto_init() {
	if File_api_logic_logic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_logic_logic_proto_rawDesc), len(file_api_logic_logic_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_logic_logic_proto_goTypes,
		DependencyIndexes: file_api_logic_logic_proto_depIdxs,
		EnumInfos:         file_api_logic_logic_proto_enumTypes,
		MessageInfos:      file_api_logic_logic_proto_msgTypes,
	}.Build()
	File_api_logic_logic_proto = out.File
	file_api_logic_logic_proto_goTypes = nil
	file_api_logic_logic_proto_depIdxs = nil
}
