// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: api/router/router.proto

package router

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Router_RouteByUser_FullMethodName         = "/goim.router.Router/RouteByUser"
	Router_RouteByRoom_FullMethodName         = "/goim.router.Router/RouteByRoom"
	Router_RouteBroadcast_FullMethodName      = "/goim.router.Router/RouteBroadcast"
	Router_HandleACK_FullMethodName           = "/goim.router.Router/HandleACK"
	Router_HandleACKWithDevice_FullMethodName = "/goim.router.Router/HandleACKWithDevice"
	Router_GetMessageStatus_FullMethodName    = "/goim.router.Router/GetMessageStatus"
	Router_GetStats_FullMethodName            = "/goim.router.Router/GetStats"
	Router_DirectPush_FullMethodName          = "/goim.router.Router/DirectPush"
)

// RouterClient is the client API for Router service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Router handles message route decisions and ACK state.
type RouterClient interface {
	// RouteByUser delivers a point-to-point user message and returns the selected path.
	RouteByUser(ctx context.Context, in *RouteByUserReq, opts ...grpc.CallOption) (*RouteByUserReply, error)
	// RouteByRoom delivers a room message.
	RouteByRoom(ctx context.Context, in *RouteByRoomReq, opts ...grpc.CallOption) (*RouteByRoomReply, error)
	// RouteBroadcast delivers a global broadcast.
	RouteBroadcast(ctx context.Context, in *RouteBroadcastReq, opts ...grpc.CallOption) (*RouteBroadcastReply, error)
	// HandleACK processes a client ACK.
	HandleACK(ctx context.Context, in *HandleACKReq, opts ...grpc.CallOption) (*HandleACKReply, error)
	// HandleACKWithDevice processes a client ACK with device/session metadata.
	HandleACKWithDevice(ctx context.Context, in *HandleACKWithDeviceReq, opts ...grpc.CallOption) (*HandleACKWithDeviceReply, error)
	// GetMessageStatus returns the current message status.
	GetMessageStatus(ctx context.Context, in *GetMessageStatusReq, opts ...grpc.CallOption) (*GetMessageStatusReply, error)
	// GetStats returns Router delivery path counters.
	GetStats(ctx context.Context, in *GetStatsReq, opts ...grpc.CallOption) (*GetStatsReply, error)
	// DirectPush pushes a message to specific sessions, used by offline sync.
	DirectPush(ctx context.Context, in *DirectPushReq, opts ...grpc.CallOption) (*DirectPushReply, error)
}

type routerClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterClient(cc grpc.ClientConnInterface) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) RouteByUser(ctx context.Context, in *RouteByUserReq, opts ...grpc.CallOption) (*RouteByUserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteByUserReply)
	err := c.cc.Invoke(ctx, Router_RouteByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) RouteByRoom(ctx context.Context, in *RouteByRoomReq, opts ...grpc.CallOption) (*RouteByRoomReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteByRoomReply)
	err := c.cc.Invoke(ctx, Router_RouteByRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) RouteBroadcast(ctx context.Context, in *RouteBroadcastReq, opts ...grpc.CallOption) (*RouteBroadcastReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteBroadcastReply)
	err := c.cc.Invoke(ctx, Router_RouteBroadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) HandleACK(ctx context.Context, in *HandleACKReq, opts ...grpc.CallOption) (*HandleACKReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleACKReply)
	err := c.cc.Invoke(ctx, Router_HandleACK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) HandleACKWithDevice(ctx context.Context, in *HandleACKWithDeviceReq, opts ...grpc.CallOption) (*HandleACKWithDeviceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleACKWithDeviceReply)
	err := c.cc.Invoke(ctx, Router_HandleACKWithDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetMessageStatus(ctx context.Context, in *GetMessageStatusReq, opts ...grpc.CallOption) (*GetMessageStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageStatusReply)
	err := c.cc.Invoke(ctx, Router_GetMessageStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetStats(ctx context.Context, in *GetStatsReq, opts ...grpc.CallOption) (*GetStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsReply)
	err := c.cc.Invoke(ctx, Router_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) DirectPush(ctx context.Context, in *DirectPushReq, opts ...grpc.CallOption) (*DirectPushReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectPushReply)
	err := c.cc.Invoke(ctx, Router_DirectPush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServer is the server API for Router service.
// All implementations must embed UnimplementedRouterServer
// for forward compatibility.
//
// Router handles message route decisions and ACK state.
type RouterServer interface {
	// RouteByUser delivers a point-to-point user message and returns the selected path.
	RouteByUser(context.Context, *RouteByUserReq) (*RouteByUserReply, error)
	// RouteByRoom delivers a room message.
	RouteByRoom(context.Context, *RouteByRoomReq) (*RouteByRoomReply, error)
	// RouteBroadcast delivers a global broadcast.
	RouteBroadcast(context.Context, *RouteBroadcastReq) (*RouteBroadcastReply, error)
	// HandleACK processes a client ACK.
	HandleACK(context.Context, *HandleACKReq) (*HandleACKReply, error)
	// HandleACKWithDevice processes a client ACK with device/session metadata.
	HandleACKWithDevice(context.Context, *HandleACKWithDeviceReq) (*HandleACKWithDeviceReply, error)
	// GetMessageStatus returns the current message status.
	GetMessageStatus(context.Context, *GetMessageStatusReq) (*GetMessageStatusReply, error)
	// GetStats returns Router delivery path counters.
	GetStats(context.Context, *GetStatsReq) (*GetStatsReply, error)
	// DirectPush pushes a message to specific sessions, used by offline sync.
	DirectPush(context.Context, *DirectPushReq) (*DirectPushReply, error)
	mustEmbedUnimplementedRouterServer()
}

// UnimplementedRouterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouterServer struct{}

func (UnimplementedRouterServer) RouteByUser(context.Context, *RouteByUserReq) (*RouteByUserReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RouteByUser not implemented")
}
func (UnimplementedRouterServer) RouteByRoom(context.Context, *RouteByRoomReq) (*RouteByRoomReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RouteByRoom not implemented")
}
func (UnimplementedRouterServer) RouteBroadcast(context.Context, *RouteBroadcastReq) (*RouteBroadcastReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RouteBroadcast not implemented")
}
func (UnimplementedRouterServer) HandleACK(context.Context, *HandleACKReq) (*HandleACKReply, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleACK not implemented")
}
func (UnimplementedRouterServer) HandleACKWithDevice(context.Context, *HandleACKWithDeviceReq) (*HandleACKWithDeviceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleACKWithDevice not implemented")
}
func (UnimplementedRouterServer) GetMessageStatus(context.Context, *GetMessageStatusReq) (*GetMessageStatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageStatus not implemented")
}
func (UnimplementedRouterServer) GetStats(context.Context, *GetStatsReq) (*GetStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedRouterServer) DirectPush(context.Context, *DirectPushReq) (*DirectPushReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DirectPush not implemented")
}
func (UnimplementedRouterServer) mustEmbedUnimplementedRouterServer() {}
func (UnimplementedRouterServer) testEmbeddedByValue()                {}

// UnsafeRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterServer will
// result in compilation errors.
type UnsafeRouterServer interface {
	mustEmbedUnimplementedRouterServer()
}

func RegisterRouterServer(s grpc.ServiceRegistrar, srv RouterServer) {
	// If the following call panics, it indicates UnimplementedRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Router_ServiceDesc, srv)
}

func _Router_RouteByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteByUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).RouteByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_RouteByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).RouteByUser(ctx, req.(*RouteByUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_RouteByRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteByRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).RouteByRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_RouteByRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).RouteByRoom(ctx, req.(*RouteByRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_RouteBroadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteBroadcastReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).RouteBroadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_RouteBroadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).RouteBroadcast(ctx, req.(*RouteBroadcastReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_HandleACK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleACKReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).HandleACK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_HandleACK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).HandleACK(ctx, req.(*HandleACKReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_HandleACKWithDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleACKWithDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).HandleACKWithDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_HandleACKWithDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).HandleACKWithDevice(ctx, req.(*HandleACKWithDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetMessageStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetMessageStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_GetMessageStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetMessageStatus(ctx, req.(*GetMessageStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetStats(ctx, req.(*GetStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_DirectPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectPushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).DirectPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Router_DirectPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).DirectPush(ctx, req.(*DirectPushReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Router_ServiceDesc is the grpc.ServiceDesc for Router service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Router_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goim.router.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RouteByUser",
			Handler:    _Router_RouteByUser_Handler,
		},
		{
			MethodName: "RouteByRoom",
			Handler:    _Router_RouteByRoom_Handler,
		},
		{
			MethodName: "RouteBroadcast",
			Handler:    _Router_RouteBroadcast_Handler,
		},
		{
			MethodName: "HandleACK",
			Handler:    _Router_HandleACK_Handler,
		},
		{
			MethodName: "HandleACKWithDevice",
			Handler:    _Router_HandleACKWithDevice_Handler,
		},
		{
			MethodName: "GetMessageStatus",
			Handler:    _Router_GetMessageStatus_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Router_GetStats_Handler,
		},
		{
			MethodName: "DirectPush",
			Handler:    _Router_DirectPush_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/router/router.proto",
}
