// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/router/router.proto

package router

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteByUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ToUid         int64                  `protobuf:"varint,2,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"`
	Op            int32                  `protobuf:"varint,3,opt,name=op,proto3" json:"op,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Seq           int64                  `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteByUserReq) Reset() {
	*x = RouteByUserReq{}
	mi := &file_api_router_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteByUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteByUserReq) ProtoMessage() {}

func (x *RouteByUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteByUserReq.ProtoReflect.Descriptor instead.
func (*RouteByUserReq) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{0}
}

func (x *RouteByUserReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *RouteByUserReq) GetToUid() int64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *RouteByUserReq) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *RouteByUserReq) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RouteByUserReq) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type RouteByUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	TargetNode    string                 `protobuf:"bytes,3,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteByUserReply) Reset() {
	*x = RouteByUserReply{}
	mi := &file_api_router_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteByUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteByUserReply) ProtoMessage() {}

func (x *RouteByUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteByUserReply.ProtoReflect.Descriptor instead.
func (*RouteByUserReply) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{1}
}

func (x *RouteByUserReply) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *RouteByUserReply) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RouteByUserReply) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

func (x *RouteByUserReply) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *RouteByUserReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RouteByUserReply) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type RouteByRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            int32                  `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	RoomKey       string                 `protobuf:"bytes,2,opt,name=room_key,json=roomKey,proto3" json:"room_key,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteByRoomReq) Reset() {
	*x = RouteByRoomReq{}
	mi := &file_api_router_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteByRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteByRoomReq) ProtoMessage() {}

func (x *RouteByRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteByRoomReq.ProtoReflect.Descriptor instead.
func (*RouteByRoomReq) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{2}
}

func (x *RouteByRoomReq) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *RouteByRoomReq) GetRoomKey() string {
	if x != nil {
		return x.RoomKey
	}
	return ""
}

func (x *RouteByRoomReq) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type RouteByRoomReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteByRoomReply) Reset() {
	*x = RouteByRoomReply{}
	mi := &file_api_router_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteByRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteByRoomReply) ProtoMessage() {}

func (x *RouteByRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteByRoomReply.ProtoReflect.Descriptor instead.
func (*RouteByRoomReply) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{3}
}

type RouteBroadcastReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            int32                  `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Speed         int32                  `protobuf:"varint,2,opt,name=speed,proto3" json:"speed,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteBroadcastReq) Reset() {
	*x = RouteBroadcastReq{}
	mi := &file_api_router_router_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteBroadcastReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteBroadcastReq) ProtoMessage() {}

func (x *RouteBroadcastReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteBroadcastReq.ProtoReflect.Descriptor instead.
func (*RouteBroadcastReq) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{4}
}

func (x *RouteBroadcastReq) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *RouteBroadcastReq) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *RouteBroadcastReq) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type RouteBroadcastReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteBroadcastReply) Reset() {
	*x = RouteBroadcastReply{}
	mi := &file_api_router_router_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteBroadcastReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteBroadcastReply) ProtoMessage() {}

func (x *RouteBroadcastReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteBroadcastReply.ProtoReflect.Descriptor instead.
func (*RouteBroadcastReply) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{5}
}

type HandleACKReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleACKReq) Reset() {
	*x = HandleACKReq{}
	mi := &file_api_router_router_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleACKReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleACKReq) ProtoMessage() {}

func (x *HandleACKReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleACKReq.ProtoReflect.Descriptor instead.
func (*HandleACKReq) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{6}
}

func (x *HandleACKReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *HandleACKReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type HandleACKReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleACKReply) Reset() {
	*x = HandleACKReply{}
	mi := &file_api_router_router_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleACKReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleACKReply) ProtoMessage() {}

func (x *HandleACKReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleACKReply.ProtoReflect.Descriptor instead.
func (*HandleACKReply) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{7}
}

type HandleACKWithDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleACKWithDeviceReq) Reset() {
	*x = HandleACKWithDeviceReq{}
	mi := &file_api_router_router_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleACKWithDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleACKWithDeviceReq) ProtoMessage() {}

func (x *HandleACKWithDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleACKWithDeviceReq.ProtoReflect.Descriptor instead.
func (*HandleACKWithDeviceReq) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{8}
}

func (x *HandleACKWithDeviceReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *HandleACKWithDeviceReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *HandleACKWithDeviceReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *HandleACKWithDeviceReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HandleACKWithDeviceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleACKWithDeviceReply) Reset() {
	*x = HandleACKWithDeviceReply{}
	mi := &file_api_router_router_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleACKWithDeviceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleACKWithDeviceReply) ProtoMessage() {}

func (x *HandleACKWithDeviceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleACKWithDeviceReply.ProtoReflect.Descriptor instead.
func (*HandleACKWithDeviceReply) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{9}
}

type GetMessageStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageStatusReq) Reset() {
	*x = GetMessageStatusReq{}
	mi := &file_api_router_router_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageStatusReq) ProtoMessage() {}

func (x *GetMessageStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageStatusReq.ProtoReflect.Descriptor instead.
func (*GetMessageStatusReq) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{10}
}

func (x *GetMessageStatusReq) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type GetMessageStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageStatusReply) Reset() {
	*x = GetMessageStatusReply{}
	mi := &file_api_router_router_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageStatusReply) ProtoMessage() {}

func (x *GetMessageStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageStatusReply.ProtoReflect.Descriptor instead.
func (*GetMessageStatusReply) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{11}
}

func (x *GetMessageStatusReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsReq) Reset() {
	*x = GetStatsReq{}
	mi := &file_api_router_router_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsReq) ProtoMessage() {}

func (x *GetStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsReq.ProtoReflect.Descriptor instead.
func (*GetStatsReq) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{12}
}

type GetStatsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direct        int64                  `protobuf:"varint,1,opt,name=direct,proto3" json:"direct,omitempty"`
	Kafka         int64                  `protobuf:"varint,2,opt,name=kafka,proto3" json:"kafka,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsReply) Reset() {
	*x = GetStatsReply{}
	mi := &file_api_router_router_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsReply) ProtoMessage() {}

func (x *GetStatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsReply.ProtoReflect.Descriptor instead.
func (*GetStatsReply) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{13}
}

func (x *GetStatsReply) GetDirect() int64 {
	if x != nil {
		return x.Direct
	}
	return 0
}

func (x *GetStatsReply) GetKafka() int64 {
	if x != nil {
		return x.Kafka
	}
	return 0
}

type DirectPushReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*PushSession         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Op            int32                  `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectPushReq) Reset() {
	*x = DirectPushReq{}
	mi := &file_api_router_router_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectPushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectPushReq) ProtoMessage() {}

func (x *DirectPushReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectPushReq.ProtoReflect.Descriptor instead.
func (*DirectPushReq) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{14}
}

func (x *DirectPushReq) GetSessions() []*PushSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *DirectPushReq) GetOp() int32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *DirectPushReq) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type PushSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSession) Reset() {
	*x = PushSession{}
	mi := &file_api_router_router_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSession) ProtoMessage() {}

func (x *PushSession) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSession.ProtoReflect.Descriptor instead.
func (*PushSession) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{15}
}

func (x *PushSession) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *PushSession) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DirectPushReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FailedSessions []*PushSession         `protobuf:"bytes,1,rep,name=failed_sessions,json=failedSessions,proto3" json:"failed_sessions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DirectPushReply) Reset() {
	*x = DirectPushReply{}
	mi := &file_api_router_router_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectPushReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectPushReply) ProtoMessage() {}

func (x *DirectPushReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_router_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectPushReply.ProtoReflect.Descriptor instead.
func (*DirectPushReply) Descriptor() ([]byte, []int) {
	return file_api_router_router_proto_rawDescGZIP(), []int{16}
}

func (x *DirectPushReply) GetFailedSessions() []*PushSession {
	if x != nil {
		return x.FailedSessions
	}
	return nil
}

var File_api_router_router_proto protoreflect.FileDescriptor

const file_api_router_router_proto_rawDesc = "" +
	"\n" +
	"\x17api/router/router.proto\x12\vgoim.router\"t\n" +
	"\x0eRouteByUserReq\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x15\n" +
	"\x06to_uid\x18\x02 \x01(\x03R\x05toUid\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\x05R\x02op\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x03R\x03seq\"\xc1\x01\n" +
	"\x10RouteByUserReply\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1f\n" +
	"\vtarget_node\x18\x03 \x01(\tR\n" +
	"targetNode\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x01R\tlatencyMs\"O\n" +
	"\x0eRouteByRoomReq\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\x05R\x02op\x12\x19\n" +
	"\broom_key\x18\x02 \x01(\tR\aroomKey\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"\x12\n" +
	"\x10RouteByRoomReply\"M\n" +
	"\x11RouteBroadcastReq\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\x05R\x02op\x12\x14\n" +
	"\x05speed\x18\x02 \x01(\x05R\x05speed\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"\x15\n" +
	"\x13RouteBroadcastReply\"7\n" +
	"\fHandleACKReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\"\x10\n" +
	"\x0eHandleACKReply\"}\n" +
	"\x16HandleACKWithDeviceReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"\x1a\n" +
	"\x18HandleACKWithDeviceReply\",\n" +
	"\x13GetMessageStatusReq\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\"/\n" +
	"\x15GetMessageStatusReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\r\n" +
	"\vGetStatsReq\"=\n" +
	"\rGetStatsReply\x12\x16\n" +
	"\x06direct\x18\x01 \x01(\x03R\x06direct\x12\x14\n" +
	"\x05kafka\x18\x02 \x01(\x03R\x05kafka\"i\n" +
	"\rDirectPushReq\x124\n" +
	"\bsessions\x18\x01 \x03(\v2\x18.goim.router.PushSessionR\bsessions\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\x05R\x02op\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"7\n" +
	"\vPushSession\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"T\n" +
	"\x0fDirectPushReply\x12A\n" +
	"\x0ffailed_sessions\x18\x01 \x03(\v2\x18.goim.router.PushSessionR\x0efailedSessions2\xfe\x04\n" +
	"\x06Router\x12I\n" +
	"\vRouteByUser\x12\x1b.goim.router.RouteByUserReq\x1a\x1d.goim.router.RouteByUserReply\x12I\n" +
	"\vRouteByRoom\x12\x1b.goim.router.RouteByRoomReq\x1a\x1d.goim.router.RouteByRoomReply\x12R\n" +
	"\x0eRouteBroadcast\x12\x1e.goim.router.RouteBroadcastReq\x1a .goim.router.RouteBroadcastReply\x12C\n" +
	"\tHandleACK\x12\x19.goim.router.HandleACKReq\x1a\x1b.goim.router.HandleACKReply\x12a\n" +
	"\x13HandleACKWithDevice\x12#.goim.router.HandleACKWithDeviceReq\x1a%.goim.router.HandleACKWithDeviceReply\x12X\n" +
	"\x10GetMessageStatus\x12 .goim.router.GetMessageStatusReq\x1a\".goim.router.GetMessageStatusReply\x12@\n" +
	"\bGetStats\x12\x18.goim.router.GetStatsReq\x1a\x1a.goim.router.GetStatsReply\x12F\n" +
	"\n" +
	"DirectPush\x12\x1a.goim.router.DirectPushReq\x1a\x1c.goim.router.DirectPushReplyB-Z+github.com/Terry-Mao/goim/api/router;routerb\x06proto3"

var (
	file_api_router_router_proto_rawDescOnce sync.Once
	file_api_router_router_proto_rawDescData []byte
)

func file_api_router_router_proto_rawDescGZIP() []byte {
	file_api_router_router_proto_rawDescOnce.Do(func() {
		file_api_router_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_router_router_proto_rawDesc), len(file_api_router_router_proto_rawDesc)))
	})
	return file_api_router_router_proto_rawDescData
}

var file_api_router_router_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_router_router_proto_goTypes = []any{
	(*RouteByUserReq)(nil),           // 0: goim.router.RouteByUserReq
	(*RouteByUserReply)(nil),         // 1: goim.router.RouteByUserReply
	(*RouteByRoomReq)(nil),           // 2: goim.router.RouteByRoomReq
	(*RouteByRoomReply)(nil),         // 3: goim.router.RouteByRoomReply
	(*RouteBroadcastReq)(nil),        // 4: goim.router.RouteBroadcastReq
	(*RouteBroadcastReply)(nil),      // 5: goim.router.RouteBroadcastReply
	(*HandleACKReq)(nil),             // 6: goim.router.HandleACKReq
	(*HandleACKReply)(nil),           // 7: goim.router.HandleACKReply
	(*HandleACKWithDeviceReq)(nil),   // 8: goim.router.HandleACKWithDeviceReq
	(*HandleACKWithDeviceReply)(nil), // 9: goim.router.HandleACKWithDeviceReply
	(*GetMessageStatusReq)(nil),      // 10: goim.router.GetMessageStatusReq
	(*GetMessageStatusReply)(nil),    // 11: goim.router.GetMessageStatusReply
	(*GetStatsReq)(nil),              // 12: goim.router.GetStatsReq
	(*GetStatsReply)(nil),            // 13: goim.router.GetStatsReply
	(*DirectPushReq)(nil),            // 14: goim.router.DirectPushReq
	(*PushSession)(nil),              // 15: goim.router.PushSession
	(*DirectPushReply)(nil),          // 16: goim.router.DirectPushReply
}
var file_api_router_router_proto_depIdxs = []int32{
	15, // 0: goim.router.DirectPushReq.sessions:type_name -> goim.router.PushSession
	15, // 1: goim.router.DirectPushReply.failed_sessions:type_name -> goim.router.PushSession
	0,  // 2: goim.router.Router.RouteByUser:input_type -> goim.router.RouteByUserReq
	2,  // 3: goim.router.Router.RouteByRoom:input_type -> goim.router.RouteByRoomReq
	4,  // 4: goim.router.Router.RouteBroadcast:input_type -> goim.router.RouteBroadcastReq
	6,  // 5: goim.router.Router.HandleACK:input_type -> goim.router.HandleACKReq
	8,  // 6: goim.router.Router.HandleACKWithDevice:input_type -> goim.router.HandleACKWithDeviceReq
	10, // 7: goim.router.Router.GetMessageStatus:input_type -> goim.router.GetMessageStatusReq
	12, // 8: goim.router.Router.GetStats:input_type -> goim.router.GetStatsReq
	14, // 9: goim.router.Router.DirectPush:input_type -> goim.router.DirectPushReq
	1,  // 10: goim.router.Router.RouteByUser:output_type -> goim.router.RouteByUserReply
	3,  // 11: goim.router.Router.RouteByRoom:output_type -> goim.router.RouteByRoomReply
	5,  // 12: goim.router.Router.RouteBroadcast:output_type -> goim.router.RouteBroadcastReply
	7,  // 13: goim.router.Router.HandleACK:output_type -> goim.router.HandleACKReply
	9,  // 14: goim.router.Router.HandleACKWithDevice:output_type -> goim.router.HandleACKWithDeviceReply
	11, // 15: goim.router.Router.GetMessageStatus:output_type -> goim.router.GetMessageStatusReply
	13, // 16: goim.router.Router.GetStats:output_type -> goim.router.GetStatsReply
	16, // 17: goim.router.Router.DirectPush:output_type -> goim.router.DirectPushReply
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_router_router_proto_init() }
func file_api_router_router_proto_init() {
	if File_api_router_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_router_router_proto_rawDesc), len(file_api_router_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_router_router_proto_goTypes,
		DependencyIndexes: file_api_router_router_proto_depIdxs,
		MessageInfos:      file_api_router_router_proto_msgTypes,
	}.Build()
	File_api_router_router_proto = out.File
	file_api_router_router_proto_goTypes = nil
	file_api_router_router_proto_depIdxs = nil
}
